apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatbot

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - couchdb-statefulset.yaml
  - couchdb-service.yaml
  - rails-deployment.yaml
  - rails-service.yaml
  - rails-hpa.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
